<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="10" hostname="PC2017000051" name="withdrawal_pkg.Update_Quantity_deduction" tests="12" failures="1" timestamp="27 Dec 2017 12:35:03 GMT" time="127.026" errors="1">
  <testcase name="Befour" time="73.829" classname="withdrawal_pkg.Update_Quantity_deduction">
    <error type="org.openqa.selenium.WebDriverException" message="chrome not reachable
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.44 seconds
Build info: version: &#039;unknown&#039;, revision: &#039;unknown&#039;, time: &#039;unknown&#039;
System info: host: &#039;PC2017000051&#039;, ip: &#039;172.29.22.38&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;x86&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_131&#039;
Driver info: driver.version: ChromeDriver">
      <![CDATA[org.openqa.selenium.WebDriverException: chrome not reachable  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)Command duration or timeout: 60.44 secondsBuild info: version: 'unknown', revision: 'unknown', time: 'unknown'System info: host: 'PC2017000051', ip: '172.29.22.38', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_131'Driver info: driver.version: ChromeDriverat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)at java.lang.reflect.Constructor.newInstance(Unknown Source)at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)at java.util.stream.AbstractPipeline.copyInto(Unknown Source)at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)at java.util.stream.AbstractPipeline.evaluate(Unknown Source)at java.util.stream.ReferencePipeline.findFirst(Unknown Source)at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:184)at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:171)at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:124)at withdrawal_pkg.Update_Quantity_deduction.Befour(Update_Quantity_deduction.java:43)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeMethod(Invoker.java:516)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- Befour -->
  <testcase name="Withdrawal_creation" time="53.197" classname="withdrawal_pkg.Update_Quantity_deduction">
    <failure type="java.lang.AssertionError" message="expected [Qty Deduction Transaction has been saved successfully.] but found [Quantity Deduction]">
      <![CDATA[java.lang.AssertionError: expected [Qty Deduction Transaction has been saved successfully.] but found [Quantity Deduction]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at withdrawal_pkg.Update_Quantity_deduction.Withdrawal_creation(Update_Quantity_deduction.java:162)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- Withdrawal_creation -->
  <testcase name="Approved_by_checker" time="0.000" classname="withdrawal_pkg.Update_Quantity_deduction">
    <skipped/>
  </testcase> <!-- Approved_by_checker -->
  <testcase name="WOW_Initiat_by_wsp_maker" time="0.000" classname="withdrawal_pkg.Update_Quantity_deduction">
    <skipped/>
  </testcase> <!-- WOW_Initiat_by_wsp_maker -->
  <testcase name="WOW_Approved_by_wsp_Checker" time="0.000" classname="withdrawal_pkg.Update_Quantity_deduction">
    <skipped/>
  </testcase> <!-- WOW_Approved_by_wsp_Checker -->
  <testcase name="Discard_by_RM_Maker" time="0.000" classname="withdrawal_pkg.Update_Quantity_deduction">
    <skipped/>
  </testcase> <!-- Discard_by_RM_Maker -->
  <testcase name="Resubmit_by_RM_Maker" time="0.000" classname="withdrawal_pkg.Update_Quantity_deduction">
    <skipped/>
  </testcase> <!-- Resubmit_by_RM_Maker -->
  <testcase name="Resubmit_Txn_Approved_by_RM_Checker" time="0.000" classname="withdrawal_pkg.Update_Quantity_deduction">
    <skipped/>
  </testcase> <!-- Resubmit_Txn_Approved_by_RM_Checker -->
  <testcase name="Resubmit_Txn_Approved_by_RM_Checker1" time="0.000" classname="withdrawal_pkg.Update_Quantity_deduction">
    <skipped/>
  </testcase> <!-- Resubmit_Txn_Approved_by_RM_Checker1 -->
  <testcase name="Txn_Rejected_by_WSP_Checker" time="0.000" classname="withdrawal_pkg.Update_Quantity_deduction">
    <skipped/>
  </testcase> <!-- Txn_Rejected_by_WSP_Checker -->
  <testcase name="PendingTxn_resubmit_by_WSP_Maker" time="0.000" classname="withdrawal_pkg.Update_Quantity_deduction">
    <skipped/>
  </testcase> <!-- PendingTxn_resubmit_by_WSP_Maker -->
  <testcase name="Discard_by_wsp_checker" time="0.000" classname="withdrawal_pkg.Update_Quantity_deduction">
    <skipped/>
  </testcase> <!-- Discard_by_wsp_checker -->
</testsuite> <!-- withdrawal_pkg.Update_Quantity_deduction -->
