<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC2017000016" ignored="0" name="Test1" tests="1" failures="1" timestamp="17 Jan 2018 05:41:35 GMT" time="54.157" errors="0">
  <testcase name="EWR_creation_Approval" time="32.824" classname="NERL.EWR_With_Deposit_Main">
    <failure type="java.lang.AssertionError" message="expected [Deposit Transaction Details Saved Successfully.] but found [Lot/BIN Number already exists in the system for Warehouse:9009003]">
      <![CDATA[java.lang.AssertionError: expected [Deposit Transaction Details Saved Successfully.] but found [Lot/BIN Number already exists in the system for Warehouse:9009003]
	at Com.Wordpress.pages.Deposit.Result_Check(Deposit.java:481)
	at Com.Wordpress.pages.Deposit.Deposit_Page(Deposit.java:344)
	at NERL.EWR_With_Deposite.EWR_creation(EWR_With_Deposite.java:91)
	at NERL.EWR_With_Deposit_Main.EWR_creation_Approval(EWR_With_Deposit_Main.java:65)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- EWR_creation_Approval -->
</testsuite> <!-- Test1 -->
